bgd0 = "#3c3c3c"
bgd1 = "#222222"
bgd2 = "#282828"
bgd3 = "#434343"
bgd4 = "#666666"
txt1 = "#ebebeb"
txt2 = "#aeaeae"
acct = "#3e9a93"
srch = "#3c3c3c"
btns = "#ebebeb"
# bgd0 = "#ffffff"
# bgd1 = "#dddddd"
# bgd2 = "#bbbbbb"
# bgd3 = "#aaaaaa"
# bgd4 = "#999999"
# txt1 = "#222222"
# txt2 = "#555555"
# acct = "#d3869b"
# srch = "#333333"
# btns = "#333333"
