# bgd0 = "#3c3c3c"
# bgd1 = "#222222"
# bgd2 = "#282828"
# bgd3 = "#434343"
# bgd4 = "#666666"
# txt1 = "#ebebeb"
# txt2 = "#aeaeae"
# acct = "#3e9a93"
# srch = "#3c3c3c"
# btns = "#ebebeb"

bgd0 = "#000000"
bgd1 = "#0d0d0d"
bgd2 = "#000000"
bgd3 = "#0d0d0d"
bgd4 = "#444444"
txt1 = "#eeeeee"
txt2 = "#aaaaaa"
acct = "#59cd90"
srch = "#eeeeee"
btns = "#eeeeee"
