
[window]
opacity = 0.9
blur = false
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]
size = 15 

[window.padding]
x = 1
y = 1

[font.normal]
family = "JetbrainsMono Nerd Font"

[general]
import = [ "~/.config/alacritty/themes/catppuccin-mocha.toml",]
